### ISSUE TITLE
App crashes on Android when I try to select my flash file. 

### ISSUE THREAD

**Issue by badyherz** [nspire-emus/firebird#256] opened 2022-03-21 01:37 UTC
When I configure the app I can add boot1 and snapshot with no problem but when I select the flash file the app crashes.
The same flash works fine with no issues on the Windows App.
My phone is running Android 12.

What could be a reason?

**Comment by Vogtinator** [comment] 2022-03-21 08:03
No idea. Can you get the adb log?

**Comment by Vogtinator** [comment] 2022-03-21 16:43
The crash is fixed by https://github.com/nspire-emus/firebird/commit/aa39e17d446c8e62e0654db135224dc8b164e753, but the reason is that the flash file fails to open for some reason. It can't get permissions to open the file.

This is probably related to the recent Android filesystem changes which are rather painful for applications to deal with.

**Comment by Vogtinator** [comment] 2022-03-21 16:46
Probably the same as https://github.com/nspire-emus/firebird/issues/244

**Comment by Vogtinator** [comment] 2022-03-21 17:13
Hm, I think Qt doesn't pass `FLAG_GRANT_PERSISTABLE_URI_PERMISSION` to the `ACTION_OPEN_DOCUMENT` intent. That wouldn't explain why it works with boot1, but maybe it only affects URIs with write permissions (the snapshot isn't opened at all here).

If that's the case, the URI can still be used without calling `takePersistableUriPermission`, but it'll have to be reselected after restarting the app or device, otherwise it'll just fail to start the emulation.

Here's a build which should ignore `takePersistableUriPermission` failures (https://github.com/Vogtinator/firebird-fork/commit/71b09642ac15e42622767852d853a10533d75c73): https://owncloud.ritter-vogt.de/index.php/s/W8sQmSYke7upmb3

**Comment by Vogtinator** [comment] 2022-03-21 19:07
Any errors or warnings in the adb log?

**Comment by badyherz** [comment] 2022-03-21 20:47
I ran logcat and opened the app and tried to start the emulation.
Firebird doesn't seem to come up in the log. But I have no idea what I'm looking at,
[log2.txt](https://github.com/nspire-emus/firebird/files/8319163/log2.txt)
 so:

**Comment by Vogtinator** [comment] 2022-03-22 09:42
Indeed, there's nothing in that log, not even firebird starting up.

I guess this needs some deeper debugging using an Android 12 AVD.

**Comment by badyherz** [comment] 2022-03-22 22:15
I tried again and I think I found something?
Maybe this helps:
[log3.txt](https://github.com/nspire-emus/firebird/files/8328204/log3.txt)

**Comment by Vogtinator** [comment] 2022-03-23 07:49
It's pretty much what I expected:

```
03-22 23:11:51.735  1280  5236 W ContentProviderHelper: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{2a31baa 9703:org.firebird.emu/u0a433} (pid=9703, uid=10433) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
```

Question is why, because `ACTION_OPEN_DOCUMENT` was used...

**Comment by badyherz** [comment] 2022-03-23 17:46
Is there something I can do or try out?

**Comment by Vogtinator** [comment] 2022-03-23 19:54
I was able to set up an Android 12 AVD. File selection works fine inside, even taking the persistable permissions works and resuming works across device reboots. I was able to reproduce #221 though and have a fix at least for the broken UI.

It might already help to build FB against Qt 5.15.2, I'll try to get a build with that soon. If that doesn't help, I'll try a patch with `FLAG_GRANT_PERSISTABLE_URI_PERMISSION`.

**Comment by Vogtinator** [comment] 2022-03-24 21:40
Here's a build of FB (state of #257) with Qt 5.15.2: https://owncloud.ritter-vogt.de/index.php/s/W8sQmSYke7upmb3 (yes, same location)

**Comment by badyherz** [comment] 2022-03-24 23:24
I tested it out, and again it couldn't start the emulation.
I attached two logs because I have no idea when exactly I opened the app.
.
Interestingly, the configuration in the app looks different now (idk if that is important)
[log4.txt](https://github.com/nspire-emus/firebird/files/8346270/log4.txt)
[log5.txt](https://github.com/nspire-emus/firebird/files/8346271/log5.txt)
.

**Comment by badyherz** [comment] 2022-03-24 23:38
Also:
The app didn't ask for any permission. I manually gave it storage permission, tried again.
Seems to stay the same
[log6.txt](https://github.com/nspire-emus/firebird/files/8346320/log6.txt)
.

**Comment by Vogtinator** [comment] 2022-03-26 16:21
> Interestingly, the configuration in the app looks different now (idk if that is important, first one is old)

Yep, I fixed a bug which broke the UI, also reported in #221.

Just to make sure: Did you reselect the flash file after installing the test builds?

Here's a build with some possible workarounds: https://owncloud.ritter-vogt.de/index.php/s/W8sQmSYke7upmb3

Please provide the log even in the case that it works, as then it's easier to narrow down which of the changes helped.

It contains https://github.com/Vogtinator/firebird-fork/commit/b32bc3100d93afe8355c1735600f5db6c4b312c4 as well as this Qt patch:

```
diff --git a/src/plugins/platforms/android/qandroidplatformfiledialoghelper.cpp b/src/plugins/platforms/android/qandroidplatformfiledialoghelper.cpp
index 6bb3372380..84dd178212 100644
--- a/src/plugins/platforms/android/qandroidplatformfiledialoghelper.cpp
+++ b/src/plugins/platforms/android/qandroidplatformfiledialoghelper.cpp
@@ -42,6 +42,7 @@
 #include <androidjnimain.h>
 #include <jni.h>
 
+#include <QDebug>
 #include <QMimeType>
 #include <QMimeDatabase>
 #include <QRegularExpression>
@@ -225,6 +226,15 @@ bool QAndroidPlatformFileDialogHelper::show(Qt::WindowFlags windowFlags, Qt::Win
         }
     }
 
+    int flags = QJNIObjectPrivate::getStaticField<jint>(
+            JniIntentClass, "FLAG_GRANT_READ_URI_PERMISSION");
+    flags |= QJNIObjectPrivate::getStaticField<jint>(
+            JniIntentClass, "FLAG_GRANT_WRITE_URI_PERMISSION");
+    flags |= QJNIObjectPrivate::getStaticField<jint>(
+            JniIntentClass, "FLAG_GRANT_PERSISTABLE_URI_PERMISSION");
+    qDebug() << "Intent flags" << flags;
+    m_intent.callObjectMethod("setFlags", "(I)Landroid/content/Intent;", flags);
+
     if (!isDirDialog) {
         setOpenableCategory();
         setMimeTypes();
```

**Comment by Vogtinator** [comment] 2022-03-26 16:28
Also, if you go to "App Info" in the Settings, select "Firebird Emu" and then "Storage & cache", does it say anything about "External Storage"?

**Comment by Vogtinator** [comment] 2022-03-27 20:20
I think I reproduced the bug by accident and was able to fix it (fairly simple, https://github.com/nspire-emus/firebird/pull/257/commits/b1d2b49b0731bf78094411161e092750441d7567).

I ended up with a flash file which contained a space in its name. Android shows that encoded as `%20`, e.g. `content://com.android.externalstorage.documents/document/primary%3ADownload%2Ff2.img%20`. Internally, Firebird converted that to a string by using `QUrl::toString` with default parameters, which however decodes all valid characters automatically, ending up with `content://com.android.externalstorage.documents/document/primary%3ADownload%2Ff2.img`. This difference meant that Android could not find it in the internal list of URI grants, resulting in this error message. You appear to have a space in the file path as well, so you might have hit the same issue.

Please try https://owncloud.ritter-vogt.de/index.php/s/DO5h08BKxGvl5du

This build (at a different URL now) contains only the state of #257 and not the workaround and Qt patch mentioned above.

**Comment by badyherz** [comment] 2022-03-29 02:02
It seems to be working now with the last version you posted. If I find further bugs, I will mention them.
Here are two different logs of me starting the app with boot1 and flash already selected
[log7.txt](https://github.com/nspire-emus/firebird/files/8367469/log7.txt)
[log8.txt](https://github.com/nspire-emus/firebird/files/8367471/log8.txt)
.

**Comment by Vogtinator** [comment] 2022-03-30 19:45
Awesome, so the simple fix was indeed all that's needed to fix this.

> Edit: Idk if it's important but the app uses no storage permissions and didn't ask when opening.

That's intentional - the android file picker automatically grants permissions to the selected files.

**Closed by Vogtinator** 2022-03-30 19:45 UTC
Labels: bug, os:Android, need more info
