### ISSUE TITLE
Overlapping buttons on Android 5.1.1

### ISSUE THREAD

**Issue by awinterstale33** [nspire-emus/firebird#41] opened 2016-04-12 06:27 UTC
Are the del and ctrl buttons supposed to be covered up for now?  I have a Galaxy Note 4 on Android 5.1.1.
![screenshot_2016-04-07-16-44-52](https://cloud.githubusercontent.com/assets/4563006/14451417/d63d3cb4-003b-11e6-8ccc-0b2adfcfbfc7.png)

**Comment by Vogtinator** [comment] 2016-04-12 07:04
Definitely not! Except for the two misbehaving columns the layout looks fine though, so I don't know what went wrong here. The keypad layout was changed now to include key labels as well, those changes might have fixed this issue (https://github.com/Vogtinator/firebird/pull/36).
I'll upload an .apk later.

**Comment by awinterstale33** [comment] 2016-04-18 02:50
Thank you! Will you post something or should I just periodically check in?

**Comment by Vogtinator** [comment] 2016-04-18 04:13
Sorry, I haven't got around to upload the .apk yet, I'll do it today.

**Comment by Vogtinator** [comment] 2016-04-18 16:26
Try this: It contains an unfinished button label rework, so some keys look odd.
[QtApp-debug.apk.zip](https://github.com/nspire-emus/firebird/files/224214/QtApp-debug.apk.zip)

**Comment by awinterstale33** [comment] 2016-04-19 01:37
Well it definitely is an improvement! I wonder why my phone is making it
looking like that? It looks fine on my LG gpad 7.

**Comment by adriweb** [comment] 2016-04-19 15:39
So you're seeing the new button labels correctly...
but there is still some weird overlap? :o

Thank you,
Adrien Bertrand

2016-04-18 21:37 GMT-04:00 awinterstale33 <notifications@github.com>:

> Well it definitely is an improvement! I wonder why my phone is making it
> looking like that? It looks fine on my LG gpad 7.

**Comment by awinterstale33** [comment] 2016-04-21 18:56
![screenshot_2016-04-18-18-35-01](https://cloud.githubusercontent.com/assets/4563006/14720775/ece05446-07b7-11e6-902a-2f3513999c6a.png)
Sorry, I didn't know attaching a picture to the email didn't show up on the site.

**Comment by NikBarbour** [comment] 2016-07-16 19:25
Hi - great emulator, thanks for sharing it. 
I can confirm this bug, I think it's a Samsung Note 4 issue as I'm also using an Samsung Note 4 SM-N910F running LP5.0.1

The 6 buttons (3 each side) which should be either side of the direction pad, spill over onto the number section of the keyboard same as in the pics in this post. 
Also 2nd function definitions don't display. 
Tried the test.apk posted in this thread, and whilst better than the beta build 3 build appearance wise, it crashes constantly and was unusable. 

Thanks again for sharing. 
No idea how to add pics using mobile device here. Sorry.

**Comment by Vogtinator** [comment] 2016-07-17 19:09
Hi,
here's a (completely untested) build with the latest Qt 5.7.0. Maybe it solves some of your issues:
[QtApp-debug.apk.zip](https://github.com/nspire-emus/firebird/files/368087/QtApp-debug.apk.zip)

> Tried the test.apk posted in this thread, and whilst better than the beta build 3 build appearance wise, it crashes constantly and was unusable.

Can you provide some stack backtraces from the ADB log?

**Comment by NikBarbour** [comment] 2016-07-17 22:39
I don't have root access on this device as it's employer provided, but I do beta testing on another app (Aerofly2) which was crashing regularly. I found this article... 
Article to add logcat file in download folder on un-rooted device. 
http://stackoverflow.com/questions/25765366/android-logcat-send-log-entries-from-device-using-email
By adding this code as indicated this allowed logcat files to be obtained from a non rooted device. It solved their issues, I'm just suggesting this incase it helps here. 
Apologies for my complete lack of technical knowledge.
Beta build 3 looks awesome on my Shield K1, with perfect button alignment BTW. It seems to be a Note 4 issue only. 
Great emulator. Much appreciated. 
I'll report back on the build provided.

**Comment by NikBarbour** [comment] 2016-07-17 23:00
Just tried out the QtApp-Debug.apk.zip build you provided. Thanks again. 
The 2nd functions are more visible, but unfortunately the 6 keys, 3 each side of the direction pad still overlap the keyboard below on the Note4. 
See pic via Google drive link below... 
https://drive.google.com/file/d/0B6PTQr6lCNNneWZtX3RxUDc1SkU/view?usp=drivesdk
Unfortunately the build also constantly crashes again on start of emulation, whearas beta build 3 is stable with my flash image (cx cas  4.2.0).

Thanks again for your help here though. 
I'm happy to use it via my Shield K1 which works really well with build 3. Happy to test anything that helps you out though.

**Comment by Bwachtel** [comment] 2016-09-29 14:49
I know I'm late to this party,  but I just found out about this project yesterday. I was able to get it up and running on my note 7  running 6.0.1.  But I have the same issue where the buttons overlap (looks exactly like original post). Also the new layout you provided in this thread is not in the current release? I'm guess this project is abandoned, but I hope not because I think this is a brilliant idea and the emulator is. Very professionally done! 

Thanks
Bwachtel

**Comment by Vogtinator** [comment] 2016-09-29 14:54
>  I'm guess this project is abandoned, but I hope not

It's not abandoned at all, in fact I'm currently planning a major UI redesign with a UI that works on mobile as well as on desktop devices.

> because I think this is a brilliant idea and the emulator is. Very professionally done!

Thanks!

**Comment by NikBarbour** [comment] 2016-09-29 15:39
It's much appreciated and useful to me to.
I use this and also the HP Prime calc app on my phone a lot for work (mech
eng) . A ui revamp would be awesome though.

Thanks for your work on this.

On 29 Sep 2016 15:54, "Fabian Vogt" <notifications@github.com> wrote:

I'm guess this project is abandoned, but I hope not

It's not abandoned at all, in fact I'm currently planning a major UI
redesign with a UI that works on mobile as well as on desktop devices.

because I think this is a brilliant idea and the emulator is. Very
professionally done!

Thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nspire-emus/firebird/issues/41#issuecomment-250490488>,
or mute the thread

**Comment by Bwachtel** [comment] 2016-09-29 19:50
I stand corrected! I look forward to the new update! Any ETA on it so I know when to look back? No rush, just excited to try it out :)

**Comment by Vogtinator** [comment] 2016-10-29 22:58
Here is a test build with HiDPI scaling disabled. I have literally no idea whether this could work, it might even make everything worse.

[QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/560196/QtApp-debug.zip)

**Comment by adriweb** [comment] 2016-11-26 16:24
A new version has been released: https://github.com/nspire-emus/firebird/releases/latest
Please try it and see if that fixes the problem(s).

Please close the issue if it's fixed.

**Comment by NikBarbour** [comment] 2016-11-26 16:57
Unfortunately the tab and menu buttons still spill over onto the buttons
below. This is with the new posted v1. 1 build on a Samsung Note 4 SM-N910F
running LP5.0.1.

**Comment by jamesklyne** [comment] 2018-03-06 16:19
I also have the overlapping buttons, both in portrait and landscape. Also, is there a way to disable the splash screen so that the calculator opens faster? 

ZTE Axon 7
Android 7.1.1
Firebird 1.4

https://drive.google.com/file/d/1Z0CBa_kUdmfliH-cf1t05mwMutsd1ApJ/view?usp=drivesdk

https://drive.google.com/file/d/1fb5F-xNw8vMCgVQK6cgonG9y49tuFPfk/view?usp=drivesdk

**Comment by Vogtinator** [comment] 2018-03-06 16:21
The splashscreen is only shown while it's loading, if you disable it you'll have a black screen for the same period of time.

**Comment by Vogtinator** [comment] 2018-06-23 10:20
Here's a build with some of the latest changes - some warnings related to layouting the keypad got fixed, so maybe this issue does not exist anymore. Please try:

[firebird.zip](https://github.com/nspire-emus/firebird/files/2129827/firebird.zip)

**Comment by jamesklyne** [comment] 2018-06-26 17:53
Problem is still there (buttons still overlap). I never noticed before, but it also opens the settings pane when the screen autorotates (both versions, 1.4 and 1.4-beta).

**Comment by Vogtinator** [comment] 2022-10-22 08:51
Fixed with #275.

**Closed by Vogtinator** 2022-10-22 08:51 UTC
Labels: bug, os:Android
