### ISSUE TITLE
android 7 message

### ISSUE THREAD

**Issue by Jo900** [nspire-emus/firebird#110] opened 2017-11-18 15:07 UTC
I tried firebird 1.4 on android 7 and crash on exit.
I tried the 1.3 and i  got message "detected problems with app native libraries".

i need an advice, thanks

**Comment by Vogtinator** [comment] 2017-11-18 15:08
I need more details about the crash on exit. Don't use 1.3.

**Comment by Jo900** [comment] 2017-11-18 15:21
when i press screen to exit it says "app firebird crashed" reopen app ?

**Comment by Vogtinator** [comment] 2017-11-18 15:22
How do you exit it? If you're doing that using the back button, disable "save snapshot on exit" in the emulation settings.

**Comment by Jo900** [comment] 2017-11-18 18:52
pardon noob question, how i can select boot1 and other files ? i not have root permission, and it seems search only inside the "/"

**Comment by Vogtinator** [comment] 2017-11-18 18:53
You can search everywhere. Try /sdcard or /data for instance.

**Comment by Jo900** [comment] 2017-11-18 21:02
okay emulator is working good (i set properly all files), 
keep crash on exit, with or without save snap auto on exit.
There is a quit button ?? or ?

**Comment by Vogtinator** [comment] 2017-11-18 21:03
There is no quit button no.
Can you provide the adb log after a crash?

**Comment by Jo900** [comment] 2017-11-18 21:04
yes, eh tell me exact location, i'm not used on android, is first day after windows phone lol

**Comment by Vogtinator** [comment] 2017-11-18 21:20
https://support.symantec.com/en_US/article.HOWTO81826.html

**Comment by Jo900** [comment] 2017-11-22 12:01
hey, i tried, i got some issue with phone drivers, and i can hear usb sound and phone is not recognized... i'll figure out soon i hope. In meanwhile i can tell you that 1.3 not have this issue on exit, (just native libraries message at start). Version 1.4 is working good, it save snap on exit (suspending emulation Message), the app close and say "app is crashed"... on restart snap was saved anyway. If i close the app by switch on the rolling menu there is no issue. Just with back button. Hope you figure out this error message, is awesome have this calculator on the smartphone (one of many reason i switched from windows phone to android).
Thanks for help.

**Comment by Jo900** [comment] 2017-11-22 23:45
did you investigate why happen that crash on android 7 phone ? i mean if you have the way to test it

**Comment by Vogtinator** [comment] 2017-11-23 06:36
I don't, so I have to rely on crash logs.

**Comment by Jo900** [comment] 2017-11-23 14:22
this weekend i'll sent the .log

**Comment by Jo900** [comment] 2017-11-24 17:25
ok, i made the log, i have produced 5-6 crash so you have many entry into the log. Tried with snap, without snap, and without load any set on app start.  Always crash on exit (not a single time that i exit withput that crash, is systematic).
there are sensible data on that log ? i prefer to sent by email, if not i can link it here.
let me know.

**Comment by Jo900** [comment] 2017-11-24 18:31
here the log:

[android-debug.log](https://github.com/nspire-emus/firebird/files/1502340/android-debug.log)

**Comment by Jo900** [comment] 2017-11-24 19:00
if you fix the 1.4 build i can beta test and sent back debug log, you have to sent me your email.

**Comment by Vogtinator** [comment] 2017-11-24 19:07
The important part is this:

```
11-22 22:35:26.716 16950 16950 F DEBUG   : ABI: 'arm'
11-22 22:35:26.716 16950 16950 F DEBUG   : pid: 16924, tid: 16941, name: QtThread  >>> org.firebird.emu <<<
11-22 22:35:26.716 16950 16950 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3000000
11-22 22:35:26.716 16950 16950 F DEBUG   :     r0 03000000  r1 e1616ff5  r2 00000000  r3 00000000
11-22 22:35:26.716 16950 16950 F DEBUG   :     r4 dd88e0b9  r5 dd88e0b1  r6 00000000  r7 e1616ff5
11-22 22:35:26.716 16950 16950 F DEBUG   :     r8 00000011  r9 e7ca0dc0  sl c0000000  fp cf198000
11-22 22:35:26.716 16950 16950 F DEBUG   :     ip e177b248  sp cdd0abb0  lr e1612b45  pc e16120fc  cpsr 800e0030
11-22 22:35:26.719 16950 16950 F DEBUG   : 
11-22 22:35:26.719 16950 16950 F DEBUG   : backtrace:
11-22 22:35:26.719 16950 16950 F DEBUG   :     #00 pc 0006b0fc  /data/app/org.firebird.emu-1/lib/arm/libQt5Qml.so (_ZN13QQmlChangeSet5applyERKS_+115)
11-22 22:35:26.719 16950 16950 F DEBUG   :     #01 pc 0006bb41  /data/app/org.firebird.emu-1/lib/arm/libQt5Qml.so
```

So it's either a bug in Qt or memory corruption caused by firebird. I'll do a new build with Qt 5.7, maybe there's a difference.

**Comment by Jo900** [comment] 2017-11-24 19:12
can i remove the log from post ? did you downloaded ?

**Comment by Vogtinator** [comment] 2017-11-24 19:15
You can, but why?

Build with Qt 5.7.1 is here, please give it a try: [QtApp-debug.zip](https://github.com/nspire-emus/firebird/files/1502412/QtApp-debug.zip)
Note that it's completely untested.

**Comment by Jo900** [comment] 2017-11-24 19:16
the log have inside my email, accounts, macs etc, i checked, i cleaned up, i not like to post it on public.

i not have knowledge in debug, i wish i can help you.
Let me know if you need test and logs after you make new build.

**Comment by Vogtinator** [comment] 2017-11-24 19:17
> Let me know if you need test and logs after you make new build.

I already made it.

**Comment by Jo900** [comment] 2017-11-24 19:18
ah ok, i not seen was an .apk inside the .zip. I'll test now.

**Comment by Jo900** [comment] 2017-11-24 19:34
Nothing error or crash at exit, Is working fine ! 
Thank you so much. :) In this day i need that calculator emulator at lessons, i will use intensively.
I'll tell you if i find some bugs etc.
Thanks again ! :)))

**Comment by Darwinport** [comment] 2017-11-25 00:40
Build with Qt 5.7.1 solves the crash problem, but has another problems already solved from the 1.3 version, like various pushed buttons at the same time or swipe when tap the buttons...

**Comment by Vogtinator** [comment] 2017-11-25 10:27
Can you clarify which issues you're facing? It does say "Firebird v1.4-dev" in the sidebar, right? (Just to confirm that I didn't accidentially upload the wrong package)

**Comment by Darwinport** [comment] 2017-11-26 05:11
Yes "Firebird v1.4-dev" is correct, When I press a button and slide the screen moves and then the button is pressed and it is necessary to press it again to release it and continue using, this does not happen in version 1.4 which only presents the crash problem. I use last one (1.4) closing from the recent app and  tap on X

**Comment by Darwinport** [comment] 2017-11-26 05:16
Far from that, it is an excellent application, I am very satisfied with it.

**Comment by Vogtinator** [comment] 2017-11-26 10:06
Ok, so that's indeed a bug in Qt itself. I can't do much about that, I'm afraid.

**Comment by adriweb** [comment] 2019-04-25 12:06
To re-open if needed, Qt has since been updated quite a bit.

**Closed by adriweb** 2019-04-25 12:06 UTC
Labels: bug, external, os:Android
