### ISSUE TITLE
Fail to start emulation on Android Marshmallow

### ISSUE THREAD

**Issue by mashume** [nspire-emus/firebird#39] opened 2016-03-30 22:48 UTC
I took Boot1.img and Flash.img files that work well on my Mac and transferred them to my phone running Android Marshmallow and can't get the emulator to start.

I attempted to get a saved state to work, and that fails the same way.

Any ideas?

**Comment by Vogtinator** [comment] 2016-03-31 12:04
I'll need some more information. What's the exact error message?
Can you provide the android log output (adb logcat)?

**Comment by mashume** [comment] 2016-04-05 23:48
I'm afraid I can't. I didn't build it myself, nor do I have the development
kits installed anywhere. If there's a log or logging I can access from on
my android device I'll be happy to do so.

-Seth

**Comment by Legimet** [comment] 2016-04-05 23:53
I'm pretty sure you can run logcat on the device itself.

**Comment by riegaz** [comment] 2016-04-07 22:15
Here it is. First I tried to start emaultion. Then I closed firebird and again tried to start emulation. I'm on CM13

04-08 00:10:17.815 W/firebird(8437): (null):0 ((null)): Can't find surface 5
04-08 00:10:17.829 W/firebird(8437): (null):0 ((null)): Can't find surface 5
04-08 00:11:52.684 W/firebird(8437): (null):0 ((null)): Can't find surface 6
04-08 00:11:52.698 W/firebird(8437): (null):0 ((null)): Can't find surface 6
04-08 00:12:14.293 I/ActivityManager(907): Killing 8437:org.firebird.emu/u0a149 (adj 9): remove task
04-08 00:12:14.348 I/WindowState(907): WIN DEATH: Window{6b0b284 u0 org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity}
04-08 00:12:21.522 I/ActivityManager(907): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity (has extras)} from uid 10030 on display 0
04-08 00:12:21.566 I/ActivityManager(907): Start proc 14385:org.firebird.emu/u0a149 for activity org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity
04-08 00:12:21.959 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Gui.so: unused DT entry: type 0x1d arg 0x4e21a
04-08 00:12:21.980 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Network.so: unused DT entry: type 0x1d arg 0x11731
04-08 00:12:21.993 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Qml.so: unused DT entry: type 0x1d arg 0x3417d
04-08 00:12:22.008 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Quick.so: unused DT entry: type 0x1d arg 0x35b61
04-08 00:12:22.039 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Widgets.so: unused DT entry: type 0x1d arg 0x6b2bb
04-08 00:12:22.061 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5QuickParticles.so: unused DT entry: type 0x1d arg 0x3656
04-08 00:12:22.070 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5QuickWidgets.so: unused DT entry: type 0x1d arg 0x2933
04-08 00:12:22.080 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: unused DT entry: type 0x1d arg 0x8f94
04-08 00:12:22.080 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: is missing DT_SONAME will use basename as a replacement: "libqtforandroid.so"
04-08 00:12:22.091 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/bearer/libqandroidbearer.so: unused DT entry: type 0x1d arg 0x1727
04-08 00:12:22.091 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/bearer/libqandroidbearer.so: is missing DT_SONAME will use basename as a replacement: "libqandroidbearer.so"
04-08 00:12:22.107 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libfirebird.so: unused DT entry: type 0x1d arg 0xb316
04-08 00:12:22.112 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libfirebird.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
04-08 00:12:22.230 I/ActivityManager(907): Displayed org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity: +678ms
04-08 00:12:22.294 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick.2/libqtquick2plugin.so: unused DT entry: type 0x1d arg 0x4bd
04-08 00:12:22.294 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick.2/libqtquick2plugin.so: is missing DT_SONAME will use basename as a replacement: "libqtquick2plugin.so"
04-08 00:12:22.315 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Layouts/libqquicklayoutsplugin.so: unused DT entry: type 0x1d arg 0x1967
04-08 00:12:22.315 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Layouts/libqquicklayoutsplugin.so: is missing DT_SONAME will use basename as a replacement: "libqquicklayoutsplugin.so"
04-08 00:12:22.323 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Dialogs/libdialogplugin.so: unused DT entry: type 0x1d arg 0x2474
04-08 00:12:22.323 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Dialogs/libdialogplugin.so: is missing DT_SONAME will use basename as a replacement: "libdialogplugin.so"
04-08 00:12:22.337 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Controls/libqtquickcontrolsplugin.so: unused DT entry: type 0x1d arg 0x4147
04-08 00:12:22.337 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Controls/libqtquickcontrolsplugin.so: is missing DT_SONAME will use basename as a replacement: "libqtquickcontrolsplugin.so"
04-08 00:12:22.350 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Window.2/libwindowplugin.so: unused DT entry: type 0x1d arg 0x493
04-08 00:12:22.350 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Window.2/libwindowplugin.so: is missing DT_SONAME will use basename as a replacement: "libwindowplugin.so"
04-08 00:12:22.371 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin.so: unused DT entry: type 0x1d arg 0x14a1
04-08 00:12:22.371 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin.so: is missing DT_SONAME will use basename as a replacement: "libdialogsprivateplugin.so"
04-08 00:12:22.379 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so: unused DT entry: type 0x1d arg 0x1b5b
04-08 00:12:22.379 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so: is missing DT_SONAME will use basename as a replacement: "libqmlfolderlistmodelplugin.so"
04-08 00:12:22.387 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/Qt/labs/settings/libqmlsettingsplugin.so: unused DT entry: type 0x1d arg 0xb9c
04-08 00:12:22.387 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/Qt/labs/settings/libqmlsettingsplugin.so: is missing DT_SONAME will use basename as a replacement: "libqmlsettingsplugin.so"
04-08 00:12:23.131 W/firebird(14385): (null):0 ((null)): QObject::installEventFilter(): Cannot filter events for objects in a different thread.
04-08 00:12:23.188 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Controls/Styles/Android/libqtquickcontrolsandroidstyleplugin.so: unused DT entry: type 0x1d arg 0x1726
04-08 00:12:23.188 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick/Controls/Styles/Android/libqtquickcontrolsandroidstyleplugin.so: is missing DT_SONAME will use basename as a replacement: "libqtquickcontrolsandroidstyleplugin.so"
04-08 00:12:23.830 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqdds.so: unused DT entry: type 0x1d arg 0xb88
04-08 00:12:23.830 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqdds.so: is missing DT_SONAME will use basename as a replacement: "libqdds.so"
04-08 00:12:23.835 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqgif.so: unused DT entry: type 0x1d arg 0x7cd
04-08 00:12:23.835 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqgif.so: is missing DT_SONAME will use basename as a replacement: "libqgif.so"
04-08 00:12:23.840 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqicns.so: unused DT entry: type 0x1d arg 0xcb5
04-08 00:12:23.840 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqicns.so: is missing DT_SONAME will use basename as a replacement: "libqicns.so"
04-08 00:12:23.845 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqico.so: unused DT entry: type 0x1d arg 0xb25
04-08 00:12:23.845 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqico.so: is missing DT_SONAME will use basename as a replacement: "libqico.so"
04-08 00:12:23.856 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqjp2.so: unused DT entry: type 0x1d arg 0xc02
04-08 00:12:23.857 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqjp2.so: is missing DT_SONAME will use basename as a replacement: "libqjp2.so"
04-08 00:12:23.862 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqjpeg.so: unused DT entry: type 0x1d arg 0x10ca
04-08 00:12:23.862 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqjpeg.so: is missing DT_SONAME will use basename as a replacement: "libqjpeg.so"
04-08 00:12:23.868 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqmng.so: unused DT entry: type 0x1d arg 0x919
04-08 00:12:23.868 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqmng.so: is missing DT_SONAME will use basename as a replacement: "libqmng.so"
04-08 00:12:23.873 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqtga.so: unused DT entry: type 0x1d arg 0x8cd
04-08 00:12:23.874 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqtga.so: is missing DT_SONAME will use basename as a replacement: "libqtga.so"
04-08 00:12:23.886 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqtiff.so: unused DT entry: type 0x1d arg 0xc5e
04-08 00:12:23.886 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqtiff.so: is missing DT_SONAME will use basename as a replacement: "libqtiff.so"
04-08 00:12:23.891 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqwbmp.so: unused DT entry: type 0x1d arg 0x996
04-08 00:12:23.891 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqwbmp.so: is missing DT_SONAME will use basename as a replacement: "libqwbmp.so"
04-08 00:12:23.895 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqwebp.so: unused DT entry: type 0x1d arg 0xab7
04-08 00:12:23.895 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/imageformats/libqwebp.so: is missing DT_SONAME will use basename as a replacement: "libqwebp.so"
04-08 00:12:24.433 W/firebird(14385): (null):0 ((null)): Warning: No toast QML component registered!
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:10:17.815 W/firebird(8437): (null):0 ((null)): Can't find surface 5
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:10:17.829 W/firebird(8437): (null):0 ((null)): Can't find surface 5
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:11:52.684 W/firebird(8437): (null):0 ((null)): Can't find surface 6
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:11:52.698 W/firebird(8437): (null):0 ((null)): Can't find surface 6
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:14.293 I/ActivityManager(907): Killing 8437:org.firebird.emu/u0a149 (adj 9): remove task
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:14.348 I/WindowState(907): WIN DEATH: Window{6b0b284 u0 org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity}
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:21.522 I/ActivityManager(907): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity (has extras)} from uid 10030 on display 0
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:21.566 I/ActivityManager(907): Start proc 14385:org.firebird.emu/u0a149 for activity org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:21.959 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Gui.so: unused DT entry: type 0x1d arg 0x4e21a
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:21.980 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Network.so: unused DT entry: type 0x1d arg 0x11731
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:21.993 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Qml.so: unused DT entry: type 0x1d arg 0x3417d
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.008 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Quick.so: unused DT entry: type 0x1d arg 0x35b61
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.039 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5Widgets.so: unused DT entry: type 0x1d arg 0x6b2bb
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.061 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5QuickParticles.so: unused DT entry: type 0x1d arg 0x3656
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.070 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libQt5QuickWidgets.so: unused DT entry: type 0x1d arg 0x2933
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.080 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: unused DT entry: type 0x1d arg 0x8f94
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.080 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: is missing DT_SONAME will use basename as a replacement: "libqtforandroid.so"
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.091 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/bearer/libqandroidbearer.so: unused DT entry: type 0x1d arg 0x1727
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.091 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/plugins/bearer/libqandroidbearer.so: is missing DT_SONAME will use basename as a replacement: "libqandroidbearer.so"
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.107 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libfirebird.so: unused DT entry: type 0x1d arg 0xb316
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.112 W/linker  (14385): /data/app/org.firebird.emu-1/lib/arm/libfirebird.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.230 I/ActivityManager(907): Displayed org.firebird.emu/org.qtproject.qt5.android.bindings.QtActivity: +678ms
04-08 00:12:42.414 I/ActivityManager(907): 04-08 00:12:22.294 W/linker  (14385): /data/data/org.firebird.emu/qt-reserved-files/qml/QtQuick.2/libqtquick2plugin.so: unused DT entry: type 0x1d arg 0x4bd

**Comment by Vogtinator** [comment] 2016-04-07 22:19
No visible error message :-/

**Comment by riegaz** [comment] 2016-04-07 22:24
On the display it says "Couldn't start emulation". Which has to come somewhere from here: https://github.com/nspire-emus/firebird/search?utf8=%E2%9C%93&q=couldn%27t+start+emulation&type=Code

If you want, you could provide a apk with more debug information. I'm willing to try them and report back.

**Comment by adriweb** [comment] 2016-04-07 22:30
Yeah we'll have to dive into [`emu_start`](https://github.com/nspire-emus/firebird/blob/3014f3c370ebecfa95a3c3c1b77a9f634f88f3bd/core/emu.cpp#L160) and print debugging thigns there to know where things stop working, as there is a similar issue on iOS sometimes.

**Comment by riegaz** [comment] 2016-04-07 22:32
Would be a good idea to provide debugging versions to support yourself in finding bugs.

**Comment by adriweb** [comment] 2016-04-07 22:34
Well, symbols are enabled etc. (IIRC), but those help for crashes. Here, it's something else failing, so yeah, more debug messages here and there will (probably) help.
Sometime "soon" I guess...

**Comment by Vogtinator** [comment] 2016-04-07 22:53
Here you go. It prints to the error log target so it should be fairly easy to see.
It should look like
```
E/Firebird( 4815): Starting emulation...
E/Firebird( 4815): Trying to open flash...
E/Firebird( 4815): Initializing memory...
E/Firebird( 4815): Initialized.
E/Firebird( 4815): Loading boot1...
E/Firebird( 4815): Loading done.
E/Firebird( 4815): Initializing JIT...
E/Firebird( 4815): Success.
```
[QtApp-debug.apk.zip](https://github.com/nspire-emus/firebird/files/209358/QtApp-debug.apk.zip)

**Comment by riegaz** [comment] 2016-04-08 05:49
04-08 07:46:48.439 W/firebird(13348): (null):0 ((null)): Warning: No toast QML component registered!
04-08 07:46:48.439 E/Firebird(13348): Starting emulation...
04-08 07:46:48.439 E/Firebird(13348): Loading snapshot...
04-08 07:46:49.309 I/System.out(13386): intent pkg org.firebird.emu
04-08 07:46:49.309 I/System.out(13386): package:org.firebird.emu
04-08 07:47:10.010 W/firebird(13348): (null):0 ((null)): Can't find surface 1
04-08 07:47:10.031 W/firebird(13348): (null):0 ((null)): Can't find surface 1
04-08 07:47:12.017 E/Firebird(13348): Starting emulation...
04-08 07:47:12.017 E/Firebird(13348): Trying to open flash...

**Comment by Vogtinator** [comment] 2016-04-08 11:15
I didn't expect that the flash loading fails. Can you run [QtApp-debug.apk.zip](https://github.com/nspire-emus/firebird/files/210039/QtApp-debug.apk.zip) next?

**Comment by riegaz** [comment] 2016-04-08 15:17
04-08 17:16:03.176 E/Firebird(27813): Starting emulation...
04-08 17:16:03.176 E/Firebird(27813): Trying to open flash...
04-08 17:16:03.182 E/Firebird(27813): /data/data/org.firebird.emu/files/flash.bin: Permission denied

Just to tell, I tried different file Locations already. Internal, sdcard, Firebird file path.....same error

**Comment by Vogtinator** [comment] 2016-04-08 15:25
Try to download it via the web browser, the download folder should be read and writable by any app.

**Comment by riegaz** [comment] 2016-04-08 16:42
I putted the files in the download folder in first place and it gives the same result

**Comment by Vogtinator** [comment] 2016-04-08 16:44
I have no expanation why this doesn't work and can't reproduce the issue, sadly.
Can you try to chmod 777 it?

**Comment by riegaz** [comment] 2016-04-08 19:20
I changed not the owner and the group to org.Firebird.EMU

Same result

**Comment by riegaz** [comment] 2016-04-08 19:24
I just saw that the group changes back to sdcard_rw. However since the owner is set correctly, it should not matter.

**Comment by Vogtinator** [comment] 2016-04-08 19:26
Indeed. As it's not the mmap that fails, but the ```fopen(path_flash, "r+b")``` I have no idea why access is denied. The app's permissions are correct AFAICS.

**Comment by Vogtinator** [comment] 2016-04-08 19:27
It might be https://stackoverflow.com/questions/33030933/android-6-0-open-failed-eacces-permission-denied
I'll build a new apk and upload it in a few minutes.

**Comment by Vogtinator** [comment] 2016-04-08 19:31
targetSdkVersion is already below 23, so it shouldn't matter. Maybe your installed app lacks the permissions?

**Comment by riegaz** [comment] 2016-04-08 19:49
It has storage permission. If I want to turn it off, it tells me " this App was designed for an older Version of android....

**Comment by riegaz** [comment] 2016-04-08 20:09
This points out that you are still using an SDK below v23 right? It is strange that your App can change config file but not Access the Boot and flash file.

**Comment by Vogtinator** [comment] 2016-04-08 20:18
I am using SDK 23, but targetSdkVersion is set to 14 in the AndroidManifest.xml.

**Comment by adriweb** [comment] 2016-11-26 16:23
A new version has been released: https://github.com/nspire-emus/firebird/releases/latest
Please try it and see if that fixes the problem(s).

Closing the issue. Re-open if needed.

**Closed by adriweb** 2016-11-26 16:23 UTC
Labels: Android, bug
