### ISSUE TITLE
Can't input () into nspire-io

### ISSUE THREAD

**Issue by Vogtinator** [nspire-emus/firebird#46] opened 2016-05-16 11:24 UTC
nspire-io has a different mapping for Shift+'(' and Shift+')' ('[' and '{').
Although PR #44 by @denisps should allow typing in ( and ) directly, it is only possible by utilizing F1 and F2.

Any idea how to improve this?

**Comment by denisps** [comment] 2016-05-16 17:28
I can't really find a comprehensive explanation of what nspire-io is? Is it supposed to run on ndless? Is there a short instruction on how to run it?

If it runs inside the calculator system, it may be interpreting keymap::shift + keymap::pleft as something other then '(' since it knows that shift is being pressed. Does Shift+F1 work? If not, there are two ways to fix it:
- Fix the nspire-io to allow shift to be pressed while entering '('
- Add alternative combo for '(' and ')', like Alt+9 and Alt+0

**Comment by Vogtinator** [comment] 2016-05-16 19:06
nspire-io is a lib to have text input and output. It's used by most Ndless-SDK samples, duktape, micropython, squirrel, etc.

> If it runs inside the calculator system, it may be interpreting keymap::shift + keymap::pleft as something other then '(' since it knows that shift is being pressed.

See https://github.com/Vogtinator/nspire-io/blob/history/arch-nspire/nspire.c#L193

**Comment by denisps** [comment] 2016-05-16 21:33
I see. So, it's using Shift to determine which bracket to enter, so instead of "(", you get "[".

If we replace:
#define SHIFTCTRL(x, y, z) (ctrl ? (z) : shift ? (y) : (x))
with
#define SHIFTCTRL(x, y, z) (ctrl ? (shift ? (y) : (z)) : (x))
so:
Shift + 9 = (
Ctrl + Shift + 9 = [

But to be able to enter "]", I would suggest to map Ctrl+9 to '(', but Ctrl+9 is already a useful Cambo in calc and notes:
Ctrl + 9 = PgUp
Ctrl + 3 = PgDn
Ctrl + 7 = Home
Ctrl + 1 = End
Ctrl + 0 = Pad

So, I think, the best solution is to simply make Alt+9 and Alt+0 as alternative cambos for "(" and ")"
 and have:
Shift + 9 = (
Alt + 9 = (
Alt + Ctrl + 9 = [
Shift + Ctrl + 9 = ]
Alt + Ctrl + 9 = ]
Ctrl + 9 = PgUp

**Comment by denisps** [comment] 2016-05-16 22:02
I see
`        ,{Qt::Key_Question, keymap::punct}`
is also interfering with
`if(isKeyPressed(KEY_NSPIRE_DIVIDE))		return SHIFT('/','\\');`

This can easily be fixed by using a different cambo for keypad:punct. Something like ":"

The following characters may also prove to be problematic to enter: \ " < + ? ^ @ 

I think this keymap needs some comprehensive planning to be intuitive on both a pc and a handheld.

**Comment by Vogtinator** [comment] 2016-05-17 06:44
I think the issue is a bit different. On a PC, Shift + 9 = (, while on the calc, simply ( = (.
Currently pressing Shift + 9 results in Shift + (, shouldn't it only press (, without shift?

**Comment by denisps** [comment] 2016-05-17 15:46
Actually, it's impossible to implement without tying PC Alt to Calc's Shift and untying PC Shift from Calc's Shift, as PC Shift is currently tied directly to Calc's Shift, and any time it's pressed, calc OS knows about it. And if we did, we would make it way more unintuitive, especially entering uppercase with alt.

This is easy to implement:
Shift + 9 = Shift + (
Alt + 9 = (
Ctrl + Alt + 9 = Ctrl + (
Ctrl **+ Shift** + 9 = Ctrl + Shift + (
Ctrl + 9 = PgUp

It can be done by simply:
```
         ,{Qt::Key_ParenLeft, keymap::pleft}
+        ,{Qt::Key_9 | ALT, keymap::pleft}
         ,{Qt::Key_F1, keymap::pleft}
         ,{Qt::Key_ParenRight, keymap::pright}
 +       ,{Qt::Key_0 | ALT, keymap::pright}
         ,{Qt::Key_F2, keymap::pright}
```

I think it would make sense to make Alt a Shift without Calc's Shift for all cambos.

**Comment by denisps** [comment] 2016-05-17 15:59
There are also other keys. Anyway, I'll make another poll request.

**Comment by Vogtinator** [comment] 2016-05-17 16:52
> And if we did, we would make it way more unintuitive, especially entering uppercase with alt.

That's not exactly what I had in mind. Shift would still work as usual, directly tied to the calc's shift.
But if a key that doesn't make much sense with Shift (everything except A-Z) gets pressed, shift is released until the release event, except Alt is pressed as well.

**Comment by denisps** [comment] 2016-05-17 17:07
The problem is this. Events:
PC Shift Pressed = Calc Shift Pressed
PC 9 Pressed = LeftParen Pressed (But Shift is still pressed, and we can't send both Shift Release and LeftParen Press in the same time-frame as calc os may ignore one of them)
PC 9 Pressed = LeftParen Released (Even if we managed to release the Shift in the previous event, would we have to press it now in the same time frame as releasing LeftParen key?)
Now, what if PC Shift is released before PC 9? Would we just ignore i because we already released Calc Shiftt?

**Comment by Vogtinator** [comment] 2016-05-17 17:12
>  we can't send both Shift Release and LeftParen Press in the same time-frame as calc os may ignore one of them

nspire-io won't.

> Now, what if PC Shift is released before PC 9? Would we just ignore i because we already released Calc Shiftt?

That's a good question, with my hacky idea of implementation it would generate an additional 9 press as there's no release event for (.
That's exactly what happens on X11 at least as well, so probably not an issue (?).

**Comment by denisps** [comment] 2016-05-17 17:47
OK, how about:
Shift + 9 = Shift + (
Alt + Shift + 9 = (

To implement this we would do the following:
- If Alt is already pressed, don't send Shift Press Event to calc os.
- If Shift is already pressed, release Shift on Alt Press Event.

**Comment by Vogtinator** [comment] 2016-05-17 18:05
Sounds good to me!

**Comment by denisps** [comment] 2016-05-17 18:50
OK, I'll implement it and send another pull request tomorrow.

**Comment by Vogtinator** [comment] 2016-05-17 18:50
Thanks!

**Closed** 2016-06-13 17:30 UTC
