### ISSUE TITLE
Windows (possibly mac) numberpad issue

### ISSUE THREAD

**Issue by trumpetlicks** [nspire-emus/firebird#27] opened 2015-12-15 02:06 UTC
I was using this the other day, and noticed that if I wanted to do some calculations, the divide (slash /) key and multiply (star *) key of a full size keyboard's numeric pad don't create a divide or multiply within the emulator.  When the shift key is pressed to try and insert a multiply or divide using the 8 key, the actual emulator shift is pressed (which is correct), but at that point the regular multiply (star) is not active, and again the multiply is not inserted.  Also, I don't think that the parentheses or equal button of the numeric pad work either.  This might be a fairly simple fix for users if there was a key mapping capability instead of a static mapping (which is actually undocumented).

**Comment by Vogtinator** [comment] 2015-12-15 05:31
It's not really intuitive with the keymap in its current state indeed...
Multiply is mapped to Alt (or Meta/Win or Command, I don't know which key it is on Mac) and A (for "asterisk"),
divide to Alt+O. The issue is that when a normal * is typed, it is the combination of Shift and a different key, so the calculator always sees "Shift+*" in that case, which isn't really useful.

**Comment by trumpetlicks** [comment] 2015-12-15 11:51
Yeah, I was looking through the code last night (as I am a software, electrical, and systems engineer), and was trying to figure out what the fix might be LOL.

**Comment by Vogtinator** [comment] 2016-06-13 17:34
Should be fixed now too.

**Closed by Vogtinator** 2016-06-13 17:34 UTC
