### ISSUE TITLE
Crash when building flash

### ISSUE THREAD

**Issue by adammw** [nspire-emus/firebird#23] opened 2015-11-08 08:52 UTC
Compiled from master, 9f378691e79acb3ae9d16668b882d2fec28e2787 under OS X 10.10.

![screen shot 2015-11-08 at 7 47 21 pm](https://cloud.githubusercontent.com/assets/153219/11019540/a6721cd4-8651-11e5-93d1-e00a0c312356.png)

Files dumped from TI nSpire CAS (Clickpad), running OS 3.6.0.550 and ndless 3.6.

SHASUMS:
```
baf177c4844f89a53e1bc299d1b84219bb386f24  boot1.img.tns
20e96ab3cf2910f6b966debffb0d9fc70119355c  boot2.img.tns
5fd7dc24de23bd12de0fd2e778caf7b89e0c6acf  diags.img.tns
a6bcc5fe1e34781d3c319f220ab58a9d63ee002c  manuf.img.tns
```

Application crashes with backtrace:
```
Exception Type:        EXC_ARITHMETIC (SIGFPE)
Exception Codes:       EXC_I386_DIV (divide by zero)

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.github.adammw.firebird    	0x0000000100041680 load_file(unsigned char*, nand_metrics, Partition, char const*, unsigned long) + 160
1   com.github.adammw.firebird    	0x0000000100041237 flash_create_new + 199
2   com.github.adammw.firebird    	0x0000000100020985 FlashDialog::saveAs() + 1045
3   org.qt-project.QtCore         	0x0000000101940b7c QMetaObject::activate(QObject*, int, int, void**) + 2988
4   org.qt-project.QtWidgets      	0x00000001026f06e0 QAbstractButton::clicked(bool) + 64
5   org.qt-project.QtWidgets      	0x000000010244506a QAbstractButtonPrivate::emitClicked() + 58
6   org.qt-project.QtWidgets      	0x0000000102444ec8 QAbstractButtonPrivate::click() + 264
7   org.qt-project.QtWidgets      	0x0000000102445efe QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 270
8   org.qt-project.QtWidgets      	0x000000010239db2f QWidget::event(QEvent*) + 1631
9   org.qt-project.QtWidgets      	0x0000000102445c4f QAbstractButton::event(QEvent*) + 175
10  org.qt-project.QtWidgets      	0x000000010235fb3b QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
```

**Comment by adriweb** [comment] 2015-11-08 09:08
Can reproduce. This is very new, since it was fine a few commits ago.
Unfortunately, it's too late for me right now to dig in, but maybe @Vogtinator can take a look today if this also happens on Linux.

**Comment by Vogtinator** [comment] 2015-11-08 09:54
Should be fixed now, if not, reopen!

**Closed by Vogtinator** 2015-11-08 09:54 UTC
Labels: bug
