### ISSUE TITLE
Can't start emulation on Android 9 pie

### ISSUE THREAD

**Issue by jorgemcs21** [nspire-emus/firebird#144] opened 2018-12-16 19:07 UTC
I have some trouble selecting the boots and flash files.
I had to type the folder path.
After that it shows text label "Can't start emulation"
I have a Pixel 3 on stock Android.
EDIT: It does display a API error

**Comment by Vogtinator** [comment] 2018-12-17 11:09
> I have some trouble selecting the boots and flash files.
> I had to type the folder path.

That's probably the issue. What's the trouble?

**Comment by jorgemcs21** [comment] 2018-12-17 11:19
What can I do to help?

**Comment by Vogtinator** [comment] 2018-12-17 11:21
Please explain what your issue is.

Does the APK from https://github.com/nspire-emus/firebird/issues/111#issuecomment-350049067 work? If so, I'll try to integrate that better into the current code in a way that it doesn't break on my phone.

**Comment by jorgemcs21** [comment] 2018-12-17 11:38
It's easier to select the files, but doesn't work. It shows the same error on the first run stating "Detected problems with API compability. Visit ('website')"
I admit I haven't visit the URL. I'm at work and I'm a bit lazy. Do I have to worry with the security warning on installation?

**Comment by Vogtinator** [comment] 2018-12-17 12:01
> Do I have to worry with the security warning on installation?

Which warning?

**Comment by jorgemcs21** [comment] 2018-12-17 13:21
It's says the app may access data. Maybe it was from installing form a unknown source, I don't quite remember if the original one got the same warning

**Comment by Vogtinator** [comment] 2018-12-17 13:36
> It's says the app may access data.

Yup - sounds about right. I only have Android 6.0.1 here and I don't get any warning.

**Comment by Vogtinator** [comment] 2019-06-25 16:14
Please try the APK from https://github.com/nspire-emus/firebird/pull/172.

**Comment by ak2766** [comment] 2019-07-01 12:41
@Vogtinator - I've just tried the APK you pointed to above - I'm unable to select anything other than `Boot1`.  Only the first select can be selected.  The others, even using a mouse cannot be selected.

**Comment by Vogtinator** [comment] 2019-07-01 12:43
@ak2766 Do you mean that nothing happens if you click on "Select" for flash or the snapshot?
Does it work if you close and open the app again?

**Comment by ak2766** [comment] 2019-07-01 13:02
I'm running Samsung Galaxy S8+ updated to latest Android 9.0.

I'just tried the APK you suggested above.  On the first run after install after installing the 1.4-dev version, I got this error:
![SM-G955F_999(001)](https://user-images.githubusercontent.com/6629646/60438428-01080700-9c54-11e9-81c4-99c4a034e797.png)

I proceeded on hoping for the best but to no avail.  However, I was unable to select anything other than `Boot1.img`.  The other buttons could not be selected (even using a mouse).  This is what version 1.4-dev looks like (everything is so tiny):
![SM-G955F_999(002)](https://user-images.githubusercontent.com/6629646/60437687-41668580-9c52-11e9-9ecb-767aa5a6db22.png)

And here is what version 1.4 (non-dev version) looks like:
![SM-G955F_999(003)](https://user-images.githubusercontent.com/6629646/60438129-4ed03f80-9c53-11e9-9c20-9a9dec24d8c2.png)

**Comment by Vogtinator** [comment] 2019-07-01 13:06
The error message is somewhat expected, the .text relocations provide a speed boost. I'm considering turning them off for the next release though.

> This is what version 1.4-dev looks like (everything is so tiny):

That's indeed not how it should look like. There weren't any code changes in FB related to that, so I've only got Qt to blame.

**Comment by ak2766** [comment] 2019-07-01 13:22
Looks like with my version of Android (9.0), Firebird Emu is unusable due to these 2 errors:

<img src="https://user-images.githubusercontent.com/6629646/60439470-4a595600-9c56-11e9-8f0c-89617d0c33c5.png" height="500">  <img src="https://user-images.githubusercontent.com/6629646/60439477-51806400-9c56-11e9-9b79-8c012583476a.png" height="500">

**Comment by Vogtinator** [comment] 2019-07-01 13:40
The messages you see are just warnings. The failure to start emulation is likely unrelated, but here's an apk without .text relocations to test anyway: 
[firebird.zip](https://github.com/nspire-emus/firebird/files/3345824/firebird.zip)

**Comment by ak2766** [comment] 2019-07-01 13:47
Sorry - still same issue where I can only select the `Boot1.img` - the others cannot be selected.
![Selection_999(273)](https://user-images.githubusercontent.com/6629646/60441519-7ecf1100-9c5a-11e9-827c-4fb6fde7d1ab.png)

**Comment by Vogtinator** [comment] 2019-07-01 13:51
Are you using an Android emulator? If so, please provide the configuration and I'll try to reproduce the issue here.

**Comment by ak2766** [comment] 2019-07-01 14:18
Nope, this is straight off my S8+.

**Comment by ak2766** [comment] 2019-07-02 02:08
Please let me know how else I may help to get the emulator working on Android 9.

**Comment by ak2766** [comment] 2019-07-03 05:07
@Vogtinator 
I'll add that I've got the non dev `v1.4` working swimmingly under Wine on Ubuntu.

**Comment by WARmachin3** [comment] 2019-07-08 17:47
I am running Android 9 as well and getting the same errors. Also, it appears that no boot file or flash was installed when the apk was ran. I've search the drive and it wasn't loaded anywhere.

**Comment by Vogtinator** [comment] 2019-07-19 13:20
@WARmachin3 You need to provide those files yourself, see https://github.com/nspire-emus/firebird/wiki/First-Time-Setup

**Comment by Vogtinator** [comment] 2020-02-14 20:00
@ak2766 Please try this build from pr #172 (too big for GitHub): https://owncloud.ritter-vogt.de/index.php/s/dY7UpbbxuudW8vE

**Comment by ak2766** [comment] 2020-02-15 00:38
Oh wow - you are still working on it - magnificent - :).  Will try it out shortly...

**Comment by Vogtinator** [comment] 2020-02-18 09:42
@ak2766 Did you get around to testing meanwhile?

**Comment by ak2766** [comment] 2020-02-19 19:42
@Vogtinator - You've nailed it!  Works beautifully on my S8+ with Android 9.

![Selection_00196](https://user-images.githubusercontent.com/6629646/74867213-6017b900-53a8-11ea-9b40-fb8c4f88a54d.png)![Selection_00197](https://user-images.githubusercontent.com/6629646/74867221-6312a980-53a8-11ea-97bd-3464182af0e1.png)
![Selection_00198](https://user-images.githubusercontent.com/6629646/74867228-65750380-53a8-11ea-9fd4-deea2c248208.png)![Selection_00199](https://user-images.githubusercontent.com/6629646/74867234-673ec700-53a8-11ea-8485-e57e8912c516.png)
![Selection_00200](https://user-images.githubusercontent.com/6629646/74867238-69088a80-53a8-11ea-9fc3-a0fc57f41e53.png)

**Comment by Vogtinator** [comment] 2020-02-19 21:05
Great! So #172 can be merged soon and it'll be part of the next release.

**Comment by Vogtinator** [comment] 2020-02-19 21:16
@ak2766 Out of curiosity, how much time does it take from "Restart" to the Home screen?

**Comment by adriweb** [comment] 2020-02-19 21:25
And don't forget to tap on the Speed indicator (also in the sidebar, at the bottom) to make it unthrottled.

For comparison, a Release build with JIT and takes an iPhone XS around 6s to reach the homescreen.

**Comment by ak2766** [comment] 2020-02-19 22:45
> @ak2766 Out of curiosity, how much time does it take from "Restart" to the Home screen?

It's faster than me trying to start and stop a timer - :).

**Comment by adriweb** [comment] 2020-02-19 22:47
Hmm, does that mean you basically can't even see the boot progress bar?

**Comment by ak2766** [comment] 2020-02-19 22:48
I have a snapshot saved so maybe that's why.  Without a snapshot, it takes a mighty long time...

**Comment by ak2766** [comment] 2020-02-19 22:52
If you like, I can take a video of both and post here - I wonder what the limit is of attachments...

**Comment by ak2766** [comment] 2020-02-19 23:36
I just noticed that there is no `Restart` button - just `Reset` - is this what you meant?  If so, then that takes ~40 seconds.  My under 1 second statement above was to do with swiping the app closed, then starting it again using the home screen shortcut.

**Comment by Vogtinator** [comment] 2020-02-22 17:21
@ak2766 `Reset` means hot reboot, so just resetting the virtual CPU while keeping RAM and other state intact. `Restart` clears all state and reopens the flash file.

The `Restart` action in the mobile UI is actually just called `Start`, which isn't that intuitive...

~40 seconds compared to ~6s is quite long - I wonder why.

Anyway, fix for this issue is merged and will be part of v1.5.

**Closed by Vogtinator** 2020-02-22 17:21 UTC
Labels: os:Android
