### ISSUE TITLE
Keypad not working on non mobile UI on iOS

### ISSUE THREAD

**Issue by p0wer0n** [nspire-emus/firebird#9] opened 2015-07-12 00:15 UTC
When the latest commit is compiled and the mobile UI is disabled, the keypad does not work on iPhone or iPad.

**Comment by Vogtinator** [comment] 2015-07-12 00:17
It's using a QQuickWidget which might not work on iOS. AFAIK it's supported in Qt 5.5, which came out some days ago.

**Comment by p0wer0n** [comment] 2015-07-12 00:24
I will check this out. Thanks for your help.

**Comment by adriweb** [comment] 2015-07-12 00:45
Well, you may want to stay on Qt 5.4 if that's the one you have...

On 5.5, it's indeed doing things with QQuickWidgets, but crashes :/
```
0	QOpenGLFramebufferObject::handle() const	QOpenGLFramebufferObject::handle() const		0x68cf98	
1	QQuickWidgetPrivate::render(bool)	QQuickWidgetPrivate::render(bool)		0xc9824	
2	QWidget::event(QEvent *)	QWidget::event(QEvent*)		0xfa54a	
3	QQuickWidget::event(QEvent *)	QQuickWidget::event(QEvent*)		0xcb552	
4	QApplicationPrivate::notify_helper(QObject *, QEvent *)	QApplicationPrivate::notify_helper(QObject*, QEvent*)		0xd2e56	
5	QApplication::notify(QObject *, QEvent *)	QApplication::notify(QObject*, QEvent*)		0xd5490	
6	QCoreApplication::notifyInternal(QObject *, QEvent *)	QCoreApplication::notifyInternal(QObject*, QEvent*)		0xa0beb4	
7	QWidgetPrivate::show_helper()	QWidgetPrivate::show_helper()		0xf9892	
8	QWidget::setVisible(bool)	QWidget::setVisible(bool)		0xfa022	
9	QWidgetPrivate::showChildren(bool)	QWidgetPrivate::showChildren(bool)		0xf9a28	
10	QWidgetPrivate::show_helper()	QWidgetPrivate::show_helper()		0xf9794	
11	QWidgetPrivate::showChildren(bool)	QWidgetPrivate::showChildren(bool)		0xf9a20	
12	QWidgetPrivate::show_helper()	QWidgetPrivate::show_helper()		0xf9794	
13	QWidget::setVisible(bool)	QWidget::setVisible(bool)		0xfa022	
14	QWidgetPrivate::showChildren(bool)	QWidgetPrivate::showChildren(bool)		0xf9a28	
15	QWidgetPrivate::show_helper()	QWidgetPrivate::show_helper()		0xf9794	
16	QWidget::setVisible(bool)	QWidget::setVisible(bool)		0xfa022	
17	main	main.cpp	34	0x73184	
18	user_main_trampoline()	user_main_trampoline()		0x9f53e	
19	+[QIOSApplicationStateTracker applicationDidFinishLaunching]	+[QIOSApplicationStateTracker applicationDidFinishLaunching]		0x9f40a	
...	<More>				
```

**Comment by p0wer0n** [comment] 2015-07-12 00:57
I already deleted Qt 5.4 and am downloading 5.5. I'll still try it because my test device is still on iOS 6. Is Qt crashing, or is the application crashing for you?

**Comment by adriweb** [comment] 2015-07-12 01:21
It's the app that crashes (actually, both in mobile UI and non-mobile UI, but with apparently two different issues...) and they may be related to Qt 5.5... We're still looking into it

**Comment by p0wer0n** [comment] 2015-07-12 01:26
Are you testing locally from the device or did you bundle the binary as an ipa and install it?

**Comment by adriweb** [comment] 2015-07-12 01:31
From Qt Creator, I just debug it (so, it builds, deploys, and starts debugging it).
No .ipa involved.

**Comment by p0wer0n** [comment] 2015-07-12 01:40
For some reason, Qt doesn't give me an option to debug on my iPhone (iOS 8.4), or my iPad (iOS 6.1.3), so I just put the compiled binary in a folder called "Payload", zip it, rename it to an ipa, and sign it with a special code signing tool that works on 8.3+ (iModSign and InstaSign haven't been updated yet. You can find a forked version here if you ever need it: https://github.com/p0wer0n/iPAFine

**Comment by adriweb** [comment] 2015-07-12 02:15
I think I've located the issue - https://bugreports.qt.io/browse/QTBUG-46937 looks like it's the root cause.
So, we shall wait for a bit until 5.5.1 comes out... or we can try rebuilding the Qt component in question.

**Comment by Vogtinator** [comment] 2015-09-19 19:55
A workaround is to disable docks mode by commenting out the function setUIMode in mainwindow.cpp.

**Comment by Vogtinator** [comment] 2015-09-21 17:51
The Qt 5.6 beta might work as well. As this is a bug in Qt and the desktop UI isn't really made for mobile, I'm going to close this for now. If it doesn't work with disabled docks or 5.6, please reopen!

**Closed by Vogtinator** 2015-09-21 17:51 UTC
Labels: bug
