### ISSUE TITLE
Crash on startup on WIndows 

### ISSUE THREAD

**Issue by ktkwon00** [nspire-emus/firebird#117] opened 2018-01-16 06:45 UTC
When opened on Windows 10, executable opens 2 windows (the main window and the configuration) and crashed, saying "firebird-emu-windows.exe has stopped working".

![image](https://user-images.githubusercontent.com/14355090/34975231-d35fca20-facb-11e7-91a6-fd5bbcf4599d.png)

**Comment by Vogtinator** [comment] 2018-01-16 07:47
Can you try the exe from http://jacobly.com/firebird/master/latest/?

You may need to download a program to decompress the .gz file first.

**Comment by ktkwon00** [comment] 2018-01-16 09:40
Sorry, same problem.

Might be worth noting that I recently formatted my computer, and updated to
1709 in the process.

2018-01-16 15:47 GMT+08:00 Fabian Vogt <notifications@github.com>:

**Comment by Vogtinator** [comment] 2018-01-16 09:43
It might be caused by graphics driver issues. Unfortunately I don't know how to debug such issues on windows.

**Comment by ktkwon00** [comment] 2018-01-16 10:19
Thanks a lot for the advice, forcing the executable to run on discrete
graphics fixed the problem.

2018-01-16 17:43 GMT+08:00 Fabian Vogt <notifications@github.com>:

**Comment by Vogtinator** [comment] 2018-07-10 12:47
So not a bug in firebird - closing.

**Closed by Vogtinator** 2018-07-10 12:47 UTC
